---
name: Build
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  merge_group:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        rust: [stable, beta, nightly]
        zookeeper: [3.9.4, 3.9.3, 3.9.2, 3.8.4, 3.7.2, 3.6.4, 3.5.10]
    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: rustup default ${{ matrix.rust }}
      - run: wget -O zookeeper.tar.gz https://archive.apache.org/dist/zookeeper/zookeeper-${{ matrix.zookeeper }}/apache-zookeeper-${{ matrix.zookeeper }}-bin.tar.gz
      - run: mkdir zookeeper
      - run: tar -zxvf zookeeper.tar.gz -C zookeeper --strip-components 1
      - run: ./scripts/ci-start-zookeeper
      - run: cargo test -F leader_recipe
